server:
  port: 8081
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/metest?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 20
      max-active: 100
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  #      基于注解的redis缓存设置
  mail:
    host: smtp.qq.com
    port: 587
    username: 1022681778@qq.com
    password: bogygjfeekjxbeig
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.bookmall.entity  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true